version: '3.8'

services:
  backend:
    image: andreaswidj/mini-erp-backend:v0.1.0
    container_name: mini-erp-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - ./prisma:/app/prisma
    networks:
      - mini-erp-network

  frontend:
    image: andreaswidj/mini-erp-frontend:v0.1.0
    container_name: mini-erp-frontend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - mini-erp-network

networks:
  mini-erp-network:
    driver: bridge