services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mini-erp-backend-local
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    # environment:
    #   - NODE_ENV=production
    #   - DATABASE_URL=file:/app/prisma/data.db
    #   - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://frontend:3001
    volumes:
      - ./backend/prisma:/app/prisma
    networks:
      - mini-erp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mini-erp-frontend-local
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - mini-erp-network

networks:
  mini-erp-network:
    driver: bridge
