version: "3.8"

services:
  backend:
    image: YOUR_DOCKERHUB_USERNAME/mini-erp-backend:latest
    container_name: mini-erp-backend
    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/prod.db

    volumes:
      - sqlite_data:/app/data

    networks:
      - mini-erp-network

  frontend:
    image: YOUR_DOCKERHUB_USERNAME/mini-erp-frontend:latest
    container_name: mini-erp-frontend
    restart: unless-stopped

    ports:
      - "3001:3001"

    environment:
      NODE_ENV: production

      # Ganti sesuai domain/IP VPS
      NEXT_PUBLIC_API_URL: http://YOUR_SERVER_IP:3000

    depends_on:
      - backend

    networks:
      - mini-erp-network

volumes:
  sqlite_data:

networks:
  mini-erp-network:
    driver: bridge